# ------------------------------------------------------------
# Conexion a Oracle
# ------------------------------------------------------------
spring.datasource.url=jdbc:oracle:thin:@//192.168.1.61:1521/XEPDB1
spring.datasource.username=bookstore
spring.datasource.password=bookstore123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ------------------------------------------------------------
# JPA / Hibernate
# ------------------------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ------------------------------------------------------------
# Servidor
# ------------------------------------------------------------
server.port=8080